from pathlib import Path
import json


def shap_json_to_comat(
    shap_json_path,
    output_path,
):
    """
    Convert the SHAP explanation generated by Explainable-Neurosymbolic-IDS
    into the JSON format expected by the COMAT semantic layer.
    """

    shap_json_path = Path(shap_json_path)
    output_path = Path(output_path)

    with open(shap_json_path, "r", encoding="utf-8") as f:
        shap_data = json.load(f)

    comat = {
        "prediction": {
            "label": shap_data["prediction"],
            "probability": shap_data["probability"],
        },
        "features": [],
    }

    for feat in shap_data["top_features"]:

        shap_value = float(feat["shap"])

        if shap_value > 0:
            direction = "supports_prediction"
        elif shap_value < 0:
            direction = "opposes_prediction"
        else:
            direction = "neutral"

        comat["features"].append(
            {
                "name": feat["feature"],
                "value": feat["value"],

                # Importance absolue
                "contribution": abs(shap_value),

                # Valeur SHAP réelle (signée)
                "signed_contribution": shap_value,

                # Sens de l'influence
                "direction": direction,
            }
        )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with open(
        output_path,
        "w",
        encoding="utf-8",
    ) as f:
        json.dump(
            comat,
            f,
            indent=4,
            ensure_ascii=False,
        )

    return output_path